### PR TITLE
refactored code, added time to the model, added unit tests

### PR DESCRIPTION
**Pull request by jeff-regier**
Hi Aaron, I divided bin/detect_2005UT453.jl into unit tests, since we were basically using it for testing anyway. I also refactored the code in preparation for adding time to the model.

### CODE REVIEW

**Comment by jeff-regier** [comment]
Would you try putting whatever subset of the data from the WISE_ETC directory we need into the `dat` directory, and comment in the problematic test? (It's in `test/runtests.jl`.) Thanks!

**Comment by jeff-regier** [comment]
The time the image was taken is in the model now. Once we decide whether to treat pixel values as Poisson or Gaussian, I think we should be all set to detect asteroid 2005_UT453.

**Comment by ameisner** [comment]
Hi Jeff,

Thanks for doing all of this work. I've created trimmed versions of the PSF files that amount to ~0.6 MB of data. I'm just trying to make sure I figure out how to properly add commits to this PR, since I'm not sure I've done that before.

-Aaron

**Comment by jeff-regier** [comment]
Hey Aaron, If it's easier, you could just merge this pull request and start
a new one for the commented-out unit test...either way.

**Comment by ameisner** [comment]
I just pushed a commit to the image_time branch and it's showing up in this PR, so I think we're good, assuming the unit tests pass now.

**Comment by jeff-regier** [comment]
Looks good!

**Pull request merged**
